#!/usr/bin/env node
/** Build the immediate-route stylesheet from the existing canonical cascade. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "@playwright/test";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const site = path.join(root, "site");
const index = fs.readFileSync(path.join(site, "index.html"), "utf8");
const sources = ["styles.css", "theme-569.css", "design-system.css"];
const css = Object.fromEntries(sources.map(name => [name, fs.readFileSync(path.join(site, name), "utf8")]));

function compactCss(value) {
  let output = "", quote = null, escaped = false, whitespace = false;
  for (const character of value) {
    if (quote) {
      output += character;
      if (escaped) escaped = false;
      else if (character === "\\") escaped = true;
      else if (character === quote) quote = null;
      continue;
    }
    if (character === '"' || character === "'") {
      if (whitespace && output && !"{(:;,>".includes(output.at(-1))) output += " ";
      whitespace = false; quote = character; output += character; continue;
    }
    if (/\s/.test(character)) { whitespace = true; continue; }
    if ("{}:;,>".includes(character)) {
      output = output.replace(/ $/, "");
      if (!(character === "}" && output.endsWith(";"))) output += character;
      else output = output.slice(0, -1) + character;
      whitespace = false; continue;
    }
    if (whitespace && output && !"{(:;,>".includes(output.at(-1))) output += " ";
    whitespace = false; output += character;
  }
  return output.trim() + "\n";
}

const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage();
  await page.setContent(index.replace(/<script\b[\s\S]*?<\/script>/gi, ""));
  const output = await page.evaluate(({ css }) => {
    const corePages = new Set(["dashboard", "tonight", "schedule", "games"]);
    document.querySelectorAll(".page").forEach(page => page.classList.toggle("active", corePages.has(page.id)));
    document.documentElement.dataset.theme = "dark";

    const routePattern = /\.(?:home|dashboard|tonight|calendar|game-centre|quick-game|game-hero|story-chapter|chapter-nav|chapter-return|season-file|season-state)[\w-]*/i;
    const dynamicPseudos = /::(?:before|after|marker|placeholder|backdrop)|:(?:hover|active|focus|focus-visible|focus-within|visited|target|checked|disabled|enabled|open)\b/g;
    const belongsToCore = element => {
      const page = element.closest?.(".page");
      if (!page) return true;
      if (!corePages.has(page.id)) return false;
      if (page.id === "schedule") {
        const chapter = element.closest?.(".schedule-chapter");
        if (chapter && chapter.id !== "schedule-calendar-chapter") return false;
      }
      if (page.id === "games") {
        const pane = element.closest?.(".game-centre-pane");
        if (pane && pane.dataset.gamePane !== "featured") return false;
      }
      return true;
    };
    const targetsCore = selector => {
      if (routePattern.test(selector)) return true;
      const query = selector.replace(dynamicPseudos, "");
      try {
        return [...document.querySelectorAll(query)].some(belongsToCore);
      } catch (_) {
        return false;
      }
    };
    const serialize = rules => [...rules].map(rule => {
      if (rule.type === CSSRule.STYLE_RULE) return targetsCore(rule.selectorText) ? rule.cssText : "";
      if (rule.cssRules) {
        const body = serialize(rule.cssRules);
        if (!body) return "";
        const opening = rule.cssText.slice(0, rule.cssText.indexOf("{")).trim();
        return `${opening}{${body}}`;
      }
      return [CSSRule.FONT_FACE_RULE, CSSRule.KEYFRAMES_RULE].includes(rule.type) || /^@(?:property|font-feature-values|counter-style)/.test(rule.cssText)
        ? rule.cssText : "";
    }).filter(Boolean).join("\n");
    const extract = source => {
      const style = document.createElement("style");
      style.textContent = source;
      document.head.appendChild(style);
      const result = serialize(style.sheet.cssRules);
      style.remove();
      return result;
    };
    return `/* Generated by scripts/extract_core_styles.mjs. Keep canonical rules in their source files. */\n${extract(css["styles.css"])}\n${css["theme-569.css"]}\n${extract(css["design-system.css"])}\n`;
  }, { css });
  const compact = compactCss(output);
  fs.writeFileSync(path.join(site, "core-routes.css"), compact);
  console.log(`core-routes.css=${Buffer.byteLength(compact)} bytes`);
} finally {
  await browser.close();
}
